[workspace]
members = [
    "rlisp-core"
]

[package]
name = "rlisp2"
version = "0.1.0"
authors = ["benhetherington"]

[dependencies]
rlisp-core = { path = "./rlisp-core/" }
clap = { version = "2.32.0", features = ["yaml"] }