[workspace]
members = ["rlisp-core"]

[package]
name = "rlisp"
version = "0.1.0"
authors = ["Benjamin Hetherington <b.w.hetherington@gmail.com>"]
description = "A simple Lisp interpreter made in Rust, loosely based on Scheme"

[dependencies]
rlisp-core = { path = "./rlisp-core/" }
clap = "2.32.0"