[package]
name = "http-request"
version = "0.1.0"
authors = ["Benjamin Hetherington <b.w.hetherington@gmail.com>"]
edition = "2018"

[dependencies]
minihttp = { git = "https://github.com/bwhetherington/minihttp" }