[package]
name = "rlisp-core"
version = "0.1.0"
authors = ["Benjamin Hetherington <b.w.hetherington@gmail.com>"]

[dependencies]
im = "10.2.0"
termcolor = "0.3.6"
regex = "1"
lazy_static = "1.2"
rand = "0.6"